kind: pipeline
type: docker
name: default

steps:
  - name: ping
    image: redis
    commands:
      - redis-cli -h cache ping

services:
  - name: cache
    image: redis

trigger:
  branch:
    - master
  event:
    include:
      - push
      - pull_request
