kind: pipeline
name: Codequality

platform:
  os: linux
  arch: amd64

clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: true

steps:
  - name: composer
    image: joomlaprojects/docker-images:php7.3
    commands:
      - php --version
      - composer validate --no-check-all --strict
      - composer install --no-progress --no-suggest --optimize-autoloader
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache

  - name: phpunit
    iamge: joomlaprojects/docker-images:php7.3
    commands:
      - vendor/bin/phpunit

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
