---
kind: pipeline
name: codequality

clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: true

platform:
  os: linux
  arch: amd64

steps:
  - name: pre-build
    image: joomlaprojects/docker-images:php7.3
    commands:
      - cp .env.dev .env
      - php --version
      - composer install --no-progress --prefer-dist

  - name: phpunit
    image: joomlaprojects/docker-images:php7.3
    commands:
      - php artisan key:generate
      - php artisan migrate --force
      - vendor/bin/phpunit

services:
  - name: mysql
    image: mysql:5
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: cms
      MYSQL_ROOT_PASSWORD: secret
