---
kind: pipeline
name: codequality

clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: true

platform:
  os: linux
  arch: amd64

steps:
  - name: composer
    image: joomlaprojects/docker-tools:develop
    commands:
      - php --version
      - composer validate --no-check-all --strict
      - composer install --no-progress --no-suggest --optimize-autoloader

  - name: phpunit
    image: joomlaprojects/docker-images:php7.3
    commands:
      - vendor/bin/phpunit
